# Fichier listant les paramètres du module et leurs valeurs par défaut

# Coordonnées latitude, longitude permettant d'indiquer le centre des cartes du module
zoom_center = [44.63891, 6.11608]
# Zoom par défaut utilisé pour les cartes du module
zoom_level = 12
# Couleur des traces et points du fichier GPX chargé sur la carte lors de l'édition d'une visite
map_gpx_color = "green"

# Identifiant du datasaet à utiliser pour les données SFT.
# Valeur du champ `id_dataset` de la table `gn_meta.t_datasets`.
# Devrait correspondre au paramètre "dataset_id" du fichier config/settings.ini
id_dataset = 1
# Valeur du champ `id_type` dans la table `ref_geo.bib_areas_types`.
# Par défaut, id pour l'entrée avec type_name="Mailles25*25m" et type_code="M25m"
# Sauf si modifié via les paramètre "meshes_code" et "meshes_name" du fichier config/settings.ini
id_type_maille = 33
# Identifiant de la liste d'utilisateurs réalisant des visites pour SFT.
# Valeur du champ `id_liste` dans la table `utilisateurs.t_listes`.
# Devrait correspondre au paramètre "observers_list_id" du fichier config/settings.ini
id_menu_list_user = 1
# Valeur du champ `id_liste` dans la table `taxonomie.bib_listes`.
# Par défaut, id pour l'entrée avec nom_liste="Suivi Flore Territoire"
# Sauf si modifié via les paramètre "taxon_list_name" du fichier config/settings.ini
id_list_taxon = 101
# Type de SRID utilisé pour l'export des données géographiques
export_srid = 2154
# Liste des types d'export disponible
export_available_format = ["geojson", "csv", "shapefile"]

# Gestion des messages configurables
sites_list_messages = {emptyMessage = "Aucun site à afficher.", totalMessage = "sites(s) au total"}
visits_list_messages = {emptyMessage = "Aucune visite sur ce site.", totalMessage = "visite(s) au total"}
other_visits_list_messages = {emptyMessage = "Aucune autre visite sur ce site.", totalMessage = "visite(s) au total"}

# Colonnes à afficher dans la table des sites sur la page d'accueil
sites_datatable_columns = [
    { name = "Id", title = "Identifiant du site", prop = "id_base_site", width = "90"},
    { name = "Taxon", title = "Nom du taxon", prop = "nom_taxon", width = "350"},
    { name = "Nombre visites", title = "Nombre de visites", prop = "nb_visit", width = "120"},
    { name = "Dernière visite", title = "Date de la dernière visite", prop = "date_max", width = "160"},
    { name = "Organisme", title = "Organismes des observateurs des visites", prop = "organisme", width = "200"}
]
# Colonnes à afficher dans la table des visites sur la page d'un site
visits_datatable_columns = [
    {name = "Date début", prop = "visit_date_min"},
    {name = "Date fin", prop = "visit_date_max"},
    {name = "Observateur(s)", prop = "observers"},
    {name = "Présence/ Absence ?", prop = "state"}
    # {name = "Id", prop = "id_base_visit"}
]
