# Fichier listant les paramètres du module et leurs valeurs par défaut

# Coordonnées latitude, longitude permettant d'indiquer le centre des cartes du module
zoom_center = [44.982667966765845, 6.062455200884894]
# Zoom par défaut utilisé pour les cartes du module
zoom_level = 12

# Identifiant du datasaet à utiliser pour les données SFT.
# Valeur du champ `id_dataset` de la table `gn_meta.t_datasets`.
id_dataset = 1
# Valeur du champ `id_type` dans la table `ref_geo.bib_areas_types`.
# Par défaut, id pour l'entrée avec type_name="Mailles25*25m" et type_code="M25m"
id_type_maille = 32
# Valeur du champ `id_type` dans la table `ref_geo.bib_areas_types`.
# Par défaut, id pour l'entrée avec type_name="Communes" et type_code="COM"
id_type_commune = 25
# Identifiant de la liste d'utilisateurs réalisant des visites pour SFT.
# Valeur du champ `id_liste` dans la table `utilisateurs.t_listes`.
id_menu_list_user = 1
# Valeur du champ `id_liste` dans la table `taxonomie.bib_listes`.
# Par défaut, id pour l'entrée avec nom_liste="Suivi Flore Territoire"
id_list_taxon = 30
# Type de SRID utilisé pour l'export des données géographiques
export_srid = 2154
# Liste des types d'export disponible
export_available_format = ['geojson', 'csv', 'shapefile']

# Gestion des messages configurables
zp_message = {emptyMessage = "Aucune zone à afficher ", totalMessage = "zone(s) de prospection au total"}
list_visit_message = {emptyMessage = "Aucune visite sur ce site ", totalMessage = "visites au total"}
detail_list_visit_message = {emptyMessage = "Aucune autre visite sur ce site ", totalMessage = "visites au total"}

default_zp_columns = [
    { name = "Identifiant", prop = "id_base_site", width = "90"},
    { name = "Taxon", prop = "nom_taxon", width = "350"},
    { name = "Nombre de visites", prop = "nb_visit", width = "120"},
    { name = "Date de la dernière visite", prop = "date_max", width = "160"},
    { name = "Organisme", prop = "organisme", width = "200"}
]

default_list_visit_columns = [
    { name = "Date", prop = "visit_date_min"},
    { name = "Observateur(s)", prop = "observers"},
    { name = "Présence/ Absence ?", prop = "state"}
]
